apiVersion: v1
kind: Pod
metadata:
  name: probe-demo
  namespace: default
spec:
  containers:
  - name: sise
    image: quay.io/openshiftlabs/simpleservice:0.5.0
    ports:
    - containerPort: 9876
    readinessProbe: 
      tcpSocket:
        port: 9876
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health
        port: 9876
      periodSeconds: 5
    startupProbe:
      httpGet:
        path: /health
        port: 9876
      failureThreshold: 3
      periodSeconds: 2
